name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.x

permissions:
  contents: read

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout main
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs-material==9.3.1 \
            mkdocs-include-markdown-plugin==6.0.1 \
            mkdocs-awesome-pages-plugin==2.9.2

      - name: git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - run: mkdocs gh-deploy --force
